// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-o20r9vsEuKzEJfHEVSgYhHtVWtpKf28',
    appId: '1:693139256553:web:e7325776d4ee8064016c78',
    messagingSenderId: '693139256553',
    projectId: 'kibasi',
    authDomain: 'kibasi.firebaseapp.com',
    databaseURL: 'https://kibasi.firebaseio.com',
    storageBucket: 'kibasi.appspot.com',
    measurementId: 'G-NFW9GWJ52N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApyhhiMMdkp-X1Ozy0C8R7BSqCJfVSQaI',
    appId: '1:693139256553:android:ab39d81f917a285e016c78',
    messagingSenderId: '693139256553',
    projectId: 'kibasi',
    databaseURL: 'https://kibasi.firebaseio.com',
    storageBucket: 'kibasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWbyFMLLP6a4x60S_uJaZ1F0EyQw9lZ4k',
    appId: '1:693139256553:ios:45dd72e39cee392a016c78',
    messagingSenderId: '693139256553',
    projectId: 'kibasi',
    databaseURL: 'https://kibasi.firebaseio.com',
    storageBucket: 'kibasi.appspot.com',
    androidClientId: '693139256553-1mq8vmjt917gmvnf9p3ua4vc43i14cit.apps.googleusercontent.com',
    iosClientId: '693139256553-4mh5a7nraaf3efu7bvlbu7ot3sdl959b.apps.googleusercontent.com',
    iosBundleId: 'com.kibasiowner.kibasi',
  );
}
